name: RpgInventorySystem
version: '${version}'
main: org.gang.rpgsystem.RpgInventorySystem
api-version: '1.20'
dependencies:
  bootstrap:
    RegistryPlugin:
      load: BEFORE
      required: true
      join-classpath: true # Defaults to true
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9
  - xyz.icetang.lib:kommand-core:3.1.11
  - io.github.monun:invfx-core:3.3.2
  - io.github.monun:heartbeat-coroutines:0.0.5